# Generated by Django 5.0.7 on 2024-09-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='mobile_no',
            field=models.IntegerField(verbose_name=10),
        ),
    ]
