# Generated by Django 5.0.7 on 2024-09-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0002_alter_teacher_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='mobile_no',
            field=models.IntegerField(verbose_name=11),
        ),
    ]
