# Generated by Django 5.0.7 on 2024-09-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0005_student_sid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Sid',
            new_name='S_id',
        ),
    ]
