# Generated by Django 5.0.7 on 2024-09-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0006_rename_sid_student_s_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='S_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
